Open-Pectus/Open-Pectus

openpectus/.idea/.gitignore, openpectus/.idea/codeStyles/codeStyleConfig.xml, openpectus/.idea/inspectionProfiles/Project_Default.xml, openpectus/.idea/misc.xml, openpectus/.idea/modules.xml, openpectus/.idea/openpectus.iml, openpectus/.idea/vcs.xml, openpectus/aggregator/main.py, openpectus/frontend/openapi.json, openpectus/frontend/src/app/api/index.ts, openpectus/frontend/src/app/api/models/CommandSource.ts, openpectus/frontend/src/app/api/models/ExecutableCommand.ts, openpectus/frontend/src/app/api/models/ProcessValue.ts, openpectus/frontend/src/app/api/models/ProcessValueCommand.ts, openpectus/frontend/src/app/api/services/DefaultService.ts, openpectus/frontend/src/app/details/details.module.ts, openpectus/frontend/src/app/details/process-values/process-value-commands.component.ts, openpectus/frontend/src/app/details/process-values/process-value-editor.component.ts, openpectus/frontend/src/app/details/process-values/process-value.component.ts, openpectus/frontend/src/app/details/unit-details.component.ts, openpectus/frontend/src/app/ngrx/details.actions.ts, openpectus/frontend/src/app/ngrx/details.effects.ts, openpectus/frontend/src/app/ngrx/details.reducer.ts, openpectus/frontend/src/mocks/handlers.ts
I've added an endpoint in main.py for the execution of process value commands: execute_process_value_command
=> 65 support process value command buttons

openpectus/aggregator/main.py, openpectus/frontend/openapi.json, openpectus/frontend/package.json, openpectus/frontend/src/app/api/index.ts, openpectus/frontend/src/app/api/models/ProcessUnit.ts, openpectus/frontend/src/app/api/models/UserRole.ts, openpectus/frontend/src/app/api/services/DefaultService.ts, openpectus/frontend/src/app/details/details.module.ts, openpectus/frontend/src/app/details/method-editor/method-editor.component.ts, openpectus/frontend/src/app/details/process-values/process-values.component.ts, openpectus/frontend/src/app/details/unit-details.component.ts, openpectus/frontend/src/app/ngrx/details.actions.ts, openpectus/frontend/src/app/ngrx/details.effects.ts, openpectus/frontend/src/app/ngrx/details.selectors.ts, openpectus/frontend/src/mocks/handlers.ts
I added a UserRole enum on the ProcessUnit, to be able to show it.
I think it makes sense to have it there, as the backend should already be checking whether user has access or not for that endpoint, and I can use it both to show the user their access, and in the future limit the UI depending on access.
=> Unit title, controls and user role display.

openpectus/frontend/src/app/app.module.ts, openpectus/frontend/src/app/details/method-editor/method-editor.component.ts, openpectus/frontend/src/app/details/method-editor/monaco-editor.component.ts, openpectus/frontend/src/app/details/ngrx/details.actions.ts, openpectus/frontend/src/app/details/process-diagram.component.ts, openpectus/frontend/src/app/details/process-plot.component.ts, openpectus/frontend/src/app/details/process-values/process-value-commands.component.ts, openpectus/frontend/src/app/details/process-values/process-value-editor.component.ts, openpectus/frontend/src/app/details/process-values/process-value.component.ts, openpectus/frontend/src/app/details/process-values/process-values.component.ts, openpectus/frontend/src/app/details/run-log/run-log-line.component.ts, openpectus/frontend/src/app/shared/collapsible-element.component.ts, openpectus/frontend/src/app/shared/pipes/process-value.pipe.ts, openpectus/frontend/src/app/shared/shared.module.ts
Also fixes popover from the monaco-editor
=> 109 fix collapsibleelement popovers

openpectus/frontend/src/app/details/unit-details.component.ts, openpectus/frontend/src/app/shared/collapsible-element.component.ts
By handling dragover even and using the widening of the draghandler even more.
=> Fixed elements dragged large snapping back to smaller size

.github/workflows/combined-workflows.yml
Created secrets ACR_ENDPOINT, ACR_USERNAME and ACR_PASSWORD. Login to Azure container registry added. Build and push to both Azure and Github container registries.
=> Add Azure container registry push to Github Action

DEVELOPMENT.md, openpectus/Dockerfile
Fix docs to build docker locally
=> Fix docker build

.gitignore, DEVELOPMENT.md, openpectus/.idea/misc.xml, openpectus/aggregator/aggregator.py, openpectus/aggregator/aggregator_message_handlers.py, openpectus/aggregator/aggregator_server.py, openpectus/aggregator/data/__init__.py, openpectus/aggregator/data/database.py, openpectus/aggregator/data/models.py, openpectus/aggregator/data/repository.py, openpectus/aggregator/deps.py, openpectus/aggregator/main.py, openpectus/aggregator/models.py, openpectus/aggregator/routers/dto.py, openpectus/aggregator/routers/process_unit.py, openpectus/engine/engine_reporter.py, openpectus/frontend/openapi.json, openpectus/frontend/src/app/api/models/PlotLogEntryValue.ts, openpectus/frontend/src/app/api/models/ProcessValue.ts, openpectus/frontend/src/app/api/models/ProcessValueType.ts, openpectus/frontend/src/app/details/process-plot/process-plot.placement.ts, openpectus/frontend/src/app/shared/pipes/process-value.pipe.ts, openpectus/protocol/aggregator_dispatcher.py, openpectus/protocol/models.py, openpectus/test/aggregator/test_aggregator.py, openpectus/test/aggregator/test_data.py
Not sure this should be merged yet (therefore draft PR). But if you care to look at it.
This is made for SQLAlchemy 2.0, but pydantic 1.x. There's some stuff that will change with Pydantic 2.x. We should consider when we will do the upgrade.
There's some type-related stuff with Pydantic I'm worried about. Specifically the way it type coerces.
The 5 second delay between persistsing process values is hardcoded in this PR, and should probably be pulled to some configuration.
=> 255 database persist process values

miniconda terminal.bat, openpectus/aggregator/aggregator.py, openpectus/aggregator/data/models.py, openpectus/aggregator/data/repository.py, openpectus/aggregator/models.py, openpectus/aggregator/routers/auth.py, openpectus/aggregator/routers/dto.py, openpectus/aggregator/routers/process_unit.py, openpectus/engine/demo_uod.py, openpectus/engine/engine.py, openpectus/engine/engine_reporter.py, openpectus/frontend/openapi.json, openpectus/frontend/src/app/api/models/PlotLogEntryValue.ts, openpectus/frontend/src/app/auth/auth-config.module.ts, openpectus/frontend/src/app/details/process-plot/ngrx/process-plot.reducer.ts, openpectus/frontend/src/msw/handlers.ts, openpectus/lang/exec/pinterpreter.py, openpectus/lang/exec/tags.py, openpectus/protocol/models.py, openpectus/test/engine/test_engine.py, openpectus/test/engine/test_interpreter.py, openpectus/test/protocol/test_serialization.py, sync conda packages.bat
I'd like to discuss whether it's "correct" to include a timestamp for all tag values.
=> 268 fix pydantic type coersion issues

openpectus/aggregator/aggregator.py, openpectus/aggregator/aggregator_message_handlers.py, openpectus/aggregator/aggregator_server.py, openpectus/aggregator/data/database.py, openpectus/aggregator/data/repository.py, openpectus/aggregator/routers/process_unit.py, openpectus/protocol/aggregator_dispatcher.py, openpectus/test/aggregator/test_aggregator.py, openpectus/test/aggregator/test_data.py
Remove db session from dispatch interface
=> Add request scope management

openpectus/engine/demo_uod.py
and use it for annotation and colored region in plot.
closes #292 (I have to mention this because github has broken the feature "When branches are created from issues, their pull requests are automatically linked.")
=> Produce a categorical value 

openpectus/engine/demo_uod.py, openpectus/engine/engine.py, openpectus/engine/hardware.py, openpectus/engine/labjack_hardware.py, openpectus/engine/opcua_hardware.py
Only write to writable registers
Fix error formatting to include register names
=> Only read from readable registers

.github/workflows/combined-workflows.yml
Azure are a bunch of slowpokes and haven't updated theirs yet: https://github.com/Azure/login/issues/357
https://github.com/Azure/aci-deploy/issues/75
=> Updated (most) github actions to versions using node 20

openpectus/lang/exec/uod.py, openpectus/test/engine/test_engine.py
Add tests for invocation of validated signatures
=> Add support for default argument parser

openpectus/aggregator/main.py, openpectus/engine/configuration/demo_uod.py, openpectus/engine/engine.py, openpectus/engine/hardware.py, openpectus/engine/hardware_error.py, openpectus/engine/main.py, openpectus/lang/exec/uod.py, openpectus/protocol/aggregator_dispatcher.py, openpectus/protocol/engine_dispatcher.py, openpectus/test/engine/test_composite_hardware.py, openpectus/test/engine/test_hardware.py, openpectus/test/engine/test_labjack_hardware.py, openpectus/test/engine/test_opcua_hardware.py
Add missing delegation of registers in decorator
Add documentation
Enable dispatcher logging
=> Add default implementations to set is_connected

openpectus/engine/archiver.py, openpectus/lang/exec/tags_impl.py
Change delimiter to ,
Change Mark tag delimiter to ;
=> Change file extension from csv to txt

openpectus/engine/configuration/demo_uod.py, openpectus/engine/configuration/opcua_test.py, openpectus/engine/engine.py, openpectus/engine/hardware_recovery.py
Fix missing reconnected event fired causing missing update to ConnectionStatus Add opcua_test Uod for testing with opcua test server
=> Fix error flood when disconnected

openpectus/engine/engine.py, openpectus/engine/uod_builder_api.py, openpectus/lang/exec/analyzer.py, openpectus/lang/exec/pinterpreter.py, openpectus/lang/exec/readings.py, openpectus/lang/exec/tags.py, openpectus/lang/exec/units.py, openpectus/lang/exec/uod.py, openpectus/test/engine/test_analyzer_check.py, openpectus/test/engine/test_engine.py, openpectus/test/engine/test_pint.py, openpectus/test/engine/test_units.py
Refactored units to give more safety and control while still leveraging pint for conversions.
=> 433 add unit definitions

openpectus/lang/exec/units.py, openpectus/test/engine/test_pint.py, openpectus/test/engine/test_units.py
Area, flux, wt%, vol%, permeability and absorbance units added.
=> Add additional units

openpectus/engine/configuration/demo_uod.py, openpectus/engine/main.py, openpectus/lang/exec/pinterpreter.py, openpectus/lang/exec/readings.py, openpectus/test/engine/test_uod_commands.py
Replace custom docstring cleanup code
=> Warn if uod command has no example pcode

openpectus/frontend/src/app/app.component.ts, openpectus/frontend/src/app/details/method-editor/monaco-editor.component.ts
=> Don't try using monaco editor JSON sampleServer

openpectus/engine/configuration/demo_uod.py, openpectus/engine/engine.py, openpectus/engine/main.py, openpectus/lang/exec/readings.py, openpectus/lang/exec/uod.py, openpectus/test/engine/test_uod_commands.py
Validate against multiple readings using the same tag
=> Generate example commands for regex readings

openpectus/test/engine/test_opcua_hardware.py
* Switch to threading instead of multiprocessing
* Set unique port number for each test
So far I don't observe hanging tests on Windows or Ubuntu.
=> 604 test opcua hardware sometimes hangs

openpectus/frontend/src/app/top-bar.component.ts
=> Only show MSW checkbox if build number ends with 'dev'

.vscode/launch.json, openpectus/aggregator/main.py
Also affects local dev when using -lsp. Issue is fixed
=> Fix arguments to lsp main

frontend/openapi.json, frontend/src/app/api/sdk.gen.ts, frontend/src/app/api/types.gen.ts, frontend/src/app/details/method-editor/method-editor.component.ts, frontend/src/app/details/method-editor/monaco-editor-behaviours.ts, frontend/src/app/details/method-editor/monaco-wrapper-config.ts, openpectus/aggregator/command_examples.py, openpectus/aggregator/routers/lsp.py, openpectus/engine/engine.py, openpectus/engine/internal_commands.py, openpectus/lang/exec/analyzer.py, openpectus/lang/exec/commands.py, openpectus/lang/exec/pinterpreter.py, openpectus/lang/exec/tags.py, openpectus/lang/exec/uod.py, openpectus/lang/exec/visitor.py, openpectus/lang/model/ast.py, openpectus/lang/model/parser.py, openpectus/lsp/lsp_analysis.py, openpectus/lsp/main.py, openpectus/lsp/model.py, openpectus/lsp/pylsp_plugin.py, openpectus/protocol/models.py, openpectus/test/engine/test_method_manager.py, openpectus/test/lang/test_analyzer_check.py, openpectus/test/lang/test_parser.py, openpectus/test/lsp/test_argument_specs.py, openpectus/test/lsp/test_lsp_analysis.py, pyproject.toml
I have split the changes into commits on a pretty granular level for all changes that are helpful but not necessarily deeply intertwined with the LSP improvements.
All LSP stuff which *is* deeply intertwined is collected in the last commit.
Br Eskild
=> LSP Improvements

openpectus/engine/method_manager.py, openpectus/lang/exec/pinterpreter.py, openpectus/lang/exec/runlog.py, openpectus/lang/model/ast.py, openpectus/test/engine/test_engine.py, openpectus/test/engine/test_method_manager.py, openpectus/test/engine/test_runlog.py
Runlog part done. "Remain editable" part moved to general method edit task #732
=> 721 command in method with threshold not yet satisfied should not show up in run log and should remain editable

frontend/openapi.json, frontend/src/app/api/sdk.gen.ts, frontend/src/app/api/types.gen.ts, frontend/src/app/notification-preferences.component.ts, openpectus/aggregator/aggregator.py, openpectus/aggregator/aggregator_message_handlers.py, openpectus/aggregator/command_examples.py, openpectus/aggregator/data/repository.py, openpectus/aggregator/models.py, openpectus/aggregator/routers/process_unit.py, openpectus/aggregator/routers/webpush.py, openpectus/aggregator/webpush_publisher.py, openpectus/engine/engine.py, openpectus/engine/engine_message_builder.py, openpectus/engine/engine_runner.py, openpectus/lang/exec/events.py, openpectus/lang/exec/pinterpreter.py, openpectus/lang/exec/tags_impl.py, openpectus/lang/exec/visitor.py, openpectus/lang/model/ast.py, openpectus/protocol/engine_messages.py, openpectus/test/engine/utility_methods.py
I decided to create notification objects on the Engine side and then send them to the aggregator for distribution. This has the benefit that the timestamp on the Notification object is always accurate (consider an aggregator outage with buffered notification messages)
=> Trigger web push notifications

.github/workflows/combined-workflows.yml
I am deleting the Azure resources related to this project since we only use the digital ocean deployment at https://github.openpectus.org
=> Stop deployment to Azure

openpectus/aggregator/aggregator_message_handlers.py, openpectus/lang/exec/pinterpreter.py, openpectus/lang/model/ast.py, openpectus/test/engine/test_method_manager.py
Remove unused class
Add edit support for several failing cases
=> Add aggregator validation of method coming from frontend
